### ISSUE TITLE
Registration Attributes

### ISSUE THREAD

**Issue by SlowLogicBoy** [Keboo/AutoDI#120]
Right now I can only control lifetime of my objects in [Xml Configuration](https://github.com/Keboo/AutoDI/wiki/Configuration#object-lifetime). (As far as I'm aware)
I would like to have attributes that would specify on how I want to register my classes.
For example:
```csharp
[LazySingleton]
class MySingletonService {}
[Transient]
class NewInstanceEachTime {}
[None]
class ThisIsNotRegistered {}
//No Attribute
class WhateverIsDefault {}
```

**Comment by Keboo** [comment]
I do like the idea of the attributes for specifying the equivalent of the [Maps](https://github.com/Keboo/AutoDI/wiki/Configuration#custom-mapping) and [Object Lifetime](https://github.com/Keboo/AutoDI/wiki/Configuration#object-lifetime). I struggled a bit trying to find a syntax that I felt was good enough. There is a [AutoDI.SettingsAttribute](https://github.com/Keboo/AutoDI/blob/master/AutoDI/SettingsAttribute.cs) that can be applied to the assembly but it only allows settings some of the more global settings like what is on the `<AutoDI>` tag in the FodyWeavers.xml.

With all of that said, I do think this would help make setting up the container a bit easier. Some thoughts:
1. Rather than separate attributes, I think I would want a single attribute (a little easier to discover), that takes in a [Lifetime](). So something more like `[AutoDI.LifetimeAttribute(AutoDI.Lifetime.Singleton)]` or shortened simply `[Lifetime(Lifetime.Singleton)]`.
2. I _think_ the behaviors I would expect is for these attributes, to generate the equivalent of of adding a custom Type map in the FodyWeavers.xml. So:
```C#
namespace Some.Namespace
{
    [Lifetime(Lifetime.WeakSingleton)]
    public class MyService { ... }
}
```
Would be equivalent to:
```xml
<AutoDI>
    <Type Name="Some.Namespace.MyService" Lifetime="WeakSingleton" />
</AutoDI>
```
3. The attribute based l [lifetimes](https://github.com/Keboo/AutoDI/wiki/Configuration#object-lifetime) would be added prior to parsing the config (FodyWeavers.xml). This keeps inline with the other attribute based stuff and allows for the config to override the attributes. This ordering is important for the cases where these attributes may be added in a shared library that is used by multiple projects.
4. As an additional option, the `LifetimeAttribute` could also have a TargetType property. This would allow the attribute to be specified at the assembly level in addition to specifying it directly on the class itself. So:
```C#
[assembly:AutoDI.LifetimeAttribute(AutoDI.Lifetime.LazySingleton, TargetType=typeof(MySingletonService))
```
This also has the advantage of these attributes being put in a separate file or even assembly (assuming they are public). 


What are your thoughts on this approach?

**Comment by SlowLogicBoy** [comment]
I like this approach, that definitely works for me.
As an addition to your 4th point I would like to have Behavior property also (that would probably solve my #121 problem too).
Of course by introducing TargetType and/or/maybe Behavior properties `LifetimeAttribute` is no longer an appropriate name, but that's not the point just an observation :).

**Comment by Keboo** [comment]
@SlowLogicBoy yea that is a good point. A better name would probably be `MapAttribute`. 

As for the addition of a `Behavior` property. I assume what you are looking for is a way to also specify the keys for the mapping (include base classes and interfaces). To avoid confusion with the main behaviors, I would suggest that this property simply be called `Include` (not sold on the name; might need to think more about it), and have a more limited set of options: `Class`, `BaseClasses`, `Interfaces`.

**Comment by Keboo** [comment]
@SlowLogicBoy Sorry for the long delay the cleanup from handling multiple registrations took longer than expected. 
I am publishing a preview 3.3.0 nuget that will contain the new MapAttribute. As indicated above it can be applied directly to a class, or as an assembly level attribute. When specified as an assembly attribute you can either specify a type, or you can give it a type pattern (same pattern matching rules as the Type xml element).

Let me know if you have any questions.
